### ISSUE TITLE
how to play this game..??

### ISSUE THREAD

**Issue by cloudjanak** [jgfouca/scrabble#2]

**Comment by jgfouca** [comment]
scrabble --mode=normal --add-player=yourname,HUMAN --add-player=ai_player,AI
The interface is clunky, this was mostly a test to see if I could write a decent AI.

**Comment by jgfouca** [comment]
Also, the scrabble exe has a decent --help dump if you want to see all the options.

**Comment by jgfouca** [comment]
Their are routines in my program that do something very similar to that but they are only used internally. AI_Player::make_play is the main algorithm.
