### ISSUE TITLE
File won't load because of the letter X?

### ISSUE THREAD

**Issue by forgottenbutnotgone** [jgfouca/scrabble#26]
I have attached three files "willload.tar.gz", "wontload.tar.gz", and "worksagain.tar.gz". The letter X in the word SIX is stopping the file loading. If It is replaced with the letter N, the file will load.

The original game was saved with the word SIX. I substituted the X for N to create the file that does load. 

Interestingly once another word is added to the file it will load with the word SIX in place.

[wontload.tar.gz](https://github.com/jgfouca/scrabble/files/4993035/wontload.tar.gz)
[willload.tar.gz](https://github.com/jgfouca/scrabble/files/4993038/willload.tar.gz)
[worksagain.tar.gz](https://github.com/jgfouca/scrabble/files/4993040/worksagain.tar.gz)

**Comment by jgfouca** [comment]
@forgottenbutnotgone , thanks for finding this. It has been fixed.
