### ISSUE TITLE
Core dump

### ISSUE THREAD

**Issue by forgottenbutnotgone** [jgfouca/scrabble#28]
If follow the following sequence, an error and a core dump occurs:

./scrabble play -p me -b wwf-solo
set-tray EIE-DNO
Available pieces: E(1)  I(1)  E(1)  -(0)  D(2)  N(2)  O(1)  
> recommend-play
AI attempted play: C(5,4294967295) O(5,0) D(5,1) E(5,2) I(5,3) N(5,4) E(5,5) , which failed because: MOVE C(5,4294967295) O(5,0) D(5,1) E(5,2) I(5,3) N(5,4) E(5,5)  REJECTED: your play was not fully connected along the play-line

Aborted (core dumped)

However the same steps do work if I run with the 15x15 board. (./scrabble play -p me)

**Comment by jgfouca** [comment]
Thanks, there's likely a bug in the initial-play logic for small boards not taking into account that initial plays can run off the board.
