### ISSUE TITLE
default dictionary for wwf-solo board seems to be TWL06.txt rather than WWF.txt

### ISSUE THREAD

**Issue by forgottenbutnotgone** [jgfouca/scrabble#29]
This may or may not be an issue, I am not sure. I would assume that using the wwf board would default to the WWF.txt dictionary.

./scrabble play -p me -b wwf-solo
> save testfile

Config
num players: 1
0
me|
num pieces: 7
board type: 2
dict: TWL06.txt
piece source: 0

Specifying the dictionary works.

./scrabble play -p me -b wwf-solo -g wwf.txt
> save testfile

Config
num players: 1
0
me|
num pieces: 7
board type: 2
dict: WWF.txt
piece source: 1

**Comment by jgfouca** [comment]
@forgottenbutnotgone , yes, this is a bit awkward. The default game (specified via `--game` or `-g`) is scrabble. So, your initial command was asking to play a game of scrabble using the words-with-friends solo board. The selected game type drives the default values for the other fields (like dictionary).

This command is what you want I think:
```
% ./scrabble play -p me -g wwf -b wwf-solo
```
